ARG BOOTSTRAP_BASE_IMAGE
FROM ${BOOTSTRAP_BASE_IMAGE}

COPY --chmod=0555 bootstrap.sh /usr/local/bin/bootstrap.sh
COPY --chmod=0555 bootstrap.sh /usr/local/bin/profile-db-bootstrap
COPY --chmod=0555 preview-schema.sh /usr/local/bin/preview-schema.sh
